### ISSUE TITLE
Mappers activity page is showing a double count of townlands mapped

### ISSUE THREAD

**Issue by DaCor1** [rory/osm-irish-townlands#81] opened 2015-03-25 17:45 UTC
As an example, the page for mapper MikeOS shows 6 townlands added even though he has added only 3 by the looks of it

http://www.townlands.ie/mapper/MikeOS/

**Comment by IrlJidel** [comment] 2015-03-25 18:08
Looks like duplicate relations and not a td.ie bug

http://www.openstreetmap.org/relation/4678503
http://www.openstreetmap.org/relation/4726163

**Comment by DaCor1** [comment] 2015-03-25 18:31
ah ok. My mistake

**Comment by rory** [comment] 2015-03-26 08:21
FYI I think those 2 relations don't share all the same ways, so there must be some overlapping ways there too.

Closing this as this is not a bug with this software.

**Closed by rory** 2015-03-26 08:21 UTC
